# Args: <path_to_blend_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:0>"
        }
      }
    },
    {
      "module": "loader.BlendLoader",
      "config": {
        "path": "examples/blenderkit/material.blend",
        "load_from": "Material",
        "entities": "herringbone_parquet_oak_varnished",
        "add_properties": {
          "cp_prop": "val"
        },
      }
    },
    {
      "module": "loader.BlendLoader",
      "config": {
        "path": "examples/blenderkit/table.blend",
        "load_from": "Object",
        "entities": ".*.*",
        "cf_set_obj_material": "herringbone_parquet_oak_varnished",
      }
    },
    {
      "module": "loader.BlendLoader",
      "config": {
        "path": "examples/blenderkit/light.blend",
        "load_from": "Object",
        "entities": ".*light.*"
      }
    },
    {
      "module": "loader.BlendLoader",
      "config": {
        "path": "examples/blenderkit/camera.blend",
        "load_from": "Object",
        "entities": ".*Camera.*"
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "render_normals": True,
        "samples": 350,
        "render_distance": true
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "distance": [
            {
              "module": "postprocessing.TrimRedundantChannels",
              "config": {}
            }
          ]
        }
      }
    }
  ]
}
